# PLACEHOLDER-BEGIN #
MESSAGE("-- javah sources.cmake")

SET (TEMP_JAVAH_MODULE_PATH ${MAIN_CPP_SOURCES_PATH}/javah)
SET (JAVAH_MODULE_PATH ${TEMP_JAVAH_MODULE_PATH} PARENT_SCOPE)

# PLACEHOLDER-END #
