# PLACEHOLDER-BEGIN #
MESSAGE("-- base bin.cmake")

INSTALL(PROGRAMS  "${BINARY_OUTPUT_PATH}/debug"   DESTINATION bin)
INSTALL(PROGRAMS  "${BINARY_OUTPUT_PATH}/example" DESTINATION bin)

# PLACEHOLDER-END #
