# PLACEHOLDER-BEGIN #
MESSAGE("-- main targets.cmake")

ADD_CUSTOM_TARGET(analysis    echo cccc ${MAIN_CPP_SOURCES_PATH}/*.cpp .${MAIN_INCLUDES_PATH}/*.h WORKING_DIRECTORY ${PROJECT_PATH})

MESSAGE("==== MAIN_MODULE_PATH=${MAIN_MODULE_PATH}")
MESSAGE("==== MAIN_MODULE_SOURCES=${MAIN_MODULE_SOURCES}")

ADD_EXECUTABLE(example.bin ${MAIN_MODULE_SOURCES})

TARGET_LINK_LIBRARIES(example.bin "${EXAMPLE_LINKING}")

# PLACEHOLDER-END #