# PLACEHOLDER-BEGIN #
MESSAGE("-- sh lib.cmake")

INCLUDE_CMAKE_FILE(${MAIN_CMAKE_PATH}/sh/base/lib.cmake)

IF(DISTRIBUTION STREQUAL "FreeBSD")
    #    INSTALL(FILES "${LIBRARY_OUTPUT_PATH}/freebsd.sh"                DESTINATION lib)
ENDIF()

# PLACEHOLDER-END #
